export const COUNTRIES = [
  'Zimbabwe',
  'South Africa',
  'Botswana',
  'Zambia',
  'Mozambique',
  'Malawi',
  'Tanzania',
  'Kenya',
  'Uganda',
  'Rwanda',
  'Namibia',
  'Angola',
  'Democratic Republic of the Congo',
  'United Kingdom',
  'United States',
  'Australia',
  'Canada',
  'Other',
]
