export const OCCUPATIONS = [
  'Accountant',
  'Agricultural Officer',
  'Architect',
  'Artisan',
  'Builder',
  'Business Owner',
  'Carpenter',
  'Chef / Cook',
  'Civil Servant',
  'Cleaner',
  'Clerk',
  'Community Health Worker',
  'Construction Worker',
  'Dentist',
  'Doctor',
  'Driver',
  'Electrician',
  'Engineer',
  'Farmer',
  'Financial Analyst',
  'Fisherman',
  'Gardener',
  'Government Employee',
  'Hairdresser',
  'Health Worker',
  'Homemaker',
  'Horticulturalist',
  'IT Professional',
  'Journalist',
  'Lab Technician',
  'Lawyer',
  'Lecturer',
  'Mechanic',
  'Midwife',
  'Miner',
  'Minister / Pastor',
  'Nurse',
  'Pensioner / Retired',
  'Pharmacist',
  'Physiotherapist',
  'Plumber',
  'Police Officer',
  'Primary School Teacher',
  'Radiographer',
  'Receptionist',
  'Sales Representative',
  'Secondary School Teacher',
  'Security Guard',
  'Self-Employed',
  'Social Worker',
  'Software Developer',
  'Soldier / Military',
  'Student',
  'Tailor / Dressmaker',
  'Teacher',
  'Trader / Vendor',
  'Truck Driver',
  'Unemployed',
  'University Student',
  'Veterinarian',
  'Waiter / Waitress',
  'Welder',
]
